# ===== Common blocks =====
x-common-build: &common_build
  context: .

x-common-volumes: &common_volumes
  volumes:
    - ./data:/workspace/data
    - ./models:/workspace/models
    - ./notebooks:/workspace/notebooks
    - ./src:/workspace/src

x-common-ports-tf: &common_ports_tf
  ports:
    - "${JUPYTER_PORT_TF:-8888}:8888"

x-common-ports-torch: &common_ports_torch
  ports:
    - "${JUPYTER_PORT_TORCH:-8889}:8888"

x-cuda-devices: &cuda_devices
  gpus: all

x-rocm-devices: &rocm_devices
  devices:
    - "/dev/kfd"
    - "/dev/dri"
  group_add:
    - "video"
  security_opt:
    - "seccomp=unconfined"

# ===== Services =====
services:
  tf-cpu:
    build:
      context: ./docker
      dockerfile: tf.Dockerfile
    image: "${IMAGE_BASENAME:-dl-multi-framework}:tensorflow"
    <<: [*common_volumes, *common_ports_tf]
    profiles: ["cpu"]

  torch-cpu:
    build:
      context: ./docker
      dockerfile: torch.Dockerfile
    image: "${IMAGE_BASENAME:-dl-multi-framework}:pytorch"
    <<: [*common_volumes, *common_ports_torch]
    profiles: ["cpu"]



  tf-amd:
    build:
      context: ./docker
      dockerfile: tf-rocm.Dockerfile
    image: "${IMAGE_BASENAME:-dl-multi-framework}:tensorflow-rocm"
    <<: [*common_volumes, *common_ports_tf, *rocm_devices]
    profiles: ["amd"]

  torch-amd:
    build:
      context: ./docker
      dockerfile: torch-rocm.Dockerfile
    image: "${IMAGE_BASENAME:-dl-multi-framework}:pytorch-rocm"
    <<: [*common_volumes, *common_ports_torch, *rocm_devices]
    profiles: ["amd"]
