# ===== Common blocks =====
x-common-build: &common_build
  context: .

x-common-volumes: &common_volumes
  volumes:
    - ./data:/workspace/data
    - ./models:/workspace/models
    - ./notebooks:/workspace/notebooks
    - ./src:/workspace/src

x-common-ports-tf: &common_ports_tf
  ports:
    - "${JUPYTER_PORT_TF:-8888}:8888"

x-common-ports-torch: &common_ports_torch
  ports:
    - "${JUPYTER_PORT_TORCH:-8889}:8888"

x-cuda-devices: &cuda_devices
  gpus: all

x-rocm-devices: &rocm_devices
  devices:
    - "/dev/kfd"
    - "/dev/dri"
  group_add:
    - "video"
  security_opt:
    - "seccomp=unconfined"

# ===== Services =====
services:
  tf-cpu:
    build:
      <<: *common_build
      args:
        - IMAGE=tensorflow/tensorflow:2.17.0-jupyter
        - REQ=requirements/tf-req.txt
    image: "${IMAGE_BASENAME:-dl-multi-framework}:tensorflow"
    <<: [*common_volumes, *common_ports_tf]
    profiles: ["cpu"]

  torch-cpu:
    build:
      <<: *common_build
      args:
        - IMAGE=intel/intel-extension-for-pytorch:2.8.0-pip-jupyter
        - REQ=requirements/torch-req.txt
    image: "${IMAGE_BASENAME:-dl-multi-framework}:pytorch"
    <<: [*common_volumes, *common_ports_torch]
    profiles: ["cpu"]
